kind: pipeline
name: default

volumes:
- name: cache
  temp: {}

steps:
- name: lint
  image: python:3.7
  commands:
    - pip3 install flake8
    - flake8
  when:
    event: 
      - pull_request
      - push

- name: build_dev
  image: plugins/docker
  settings:
    tag: dev-env
    target: dev
    repo: docker.netsoc.co/public/netsocadmin
    registry: docker.netsoc.co
    username:
      from_secret: registry_pub_user
    password:
      from_secret: registry_pub_token
  volumes:
  - name: cache
    path: /var/lib/docker  
  when:
    event: 
      - push
    branch: 
      - master 

- name: build_prod
  image: plugins/docker
  settings:
    tag: latest
    repo: docker.netsoc.co/netsoc/netsocadmin
    registry: docker.netsoc.co
    username:
      from_secret: registry_prod_user
    password:
      from_secret: registry_prod_token
  volumes:
  - name: cache
    path: /var/lib/docker  
  when:
    event: 
      - push
    branch: 
      - master   

- name: discord_notif_success
  image: appleboy/drone-discord
  environment:
    WEBHOOK_ID:
      from_secret: discord_webhook_id
    WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  settings:
    username: Netsoc CI
    avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
    color: "#42f483"
    message: Netsoc Admin successfully built and pushed. Build num {{build.number}}. {{build.link}}
  when:
    event: 
      - push
    branch: 
      - master 
    status:
      - success

- name: discord_notif_failure
  image: appleboy/drone-discord
  environment:
    WEBHOOK_ID:
      from_secret: discord_webhook_id
    WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  settings:
    username: Netsoc CI
    avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
    color: "#e04414"
    message: Netsoc Admin failed for {{build.author}}. Build num {{build.number}}. {{build.link}}
  when:
    event: 
      - push
    branch: 
      - master 
    status:
      - failure

---
kind: secret
name: registry_prod_user
get:
  path: docker_registry/harbor
  name: harbor_priv_user

---
kind: secret
name: registry_prod_token
get:
  path: docker_registry/harbor
  name: harbor_priv_token
    
---
kind: secret
name: registry_pub_user
get:
  path: docker_registry/harbor
  name: harbor_pub_user

---
kind: secret
name: registry_pub_token
get:
  path: docker_registry/harbor
  name: harbor_pub_token
        
---
kind: secret
name: discord_webhook_id
get:
  path: discord/sysadmins_webhook
  name: discord_webhook_id

---
kind: secret
name: discord_webhook_token
get:
  path: discord/sysadmins_webhook
  name: discord_webhook_token      